### ISSUE TITLE
Automatic folder detection

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/WhatsApp-Cleaner#14]
According to present scenario, if a folder gets created inside WhatsApp Folder (/storage)
it can't be shown in the main screen of the app. To achieve this first folders inside the main folder to be fetched and then the contents.

As now all the cards are manually added like images, videos, etc.

**Comment by ngwutadesmond** [comment]
I will look into this and give you an update

**Comment by ngwutadesmond** [comment]
I will look into this and send you an updated

**Comment by pawank0411** [comment]
any updates? @chydee

**Comment by ngwutadesmond** [comment]
Not yet I'm currently going through the code base to have a basic understanding of how things work that I'll know how and what to do without messing things up. Is there a way I can reach your DM? I saw something in the code which I don't fully understand and I'd like us to discuss so you can shed more light on it and I'll also learn

**Comment by ngwutadesmond** [comment]
Thank you @Pawan0411

**Comment by pawank0411** [comment]
yes sure @chydee 
LinkedIn account : https://www.linkedin.com/in/pawan-kumar-gorai-b79508161/

**Comment by pawank0411** [comment]
any updates @chydee

**Comment by ngwutadesmond** [comment]
Nope, I don't really understand this issue if you can make it more elaborate, that'd be nice

**Comment by pawank0411** [comment]
solved.
