### ISSUE TITLE
Replace progress Dailog with new material design

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/WhatsApp-Cleaner#15]
Reference : 
[Linear Progress Indicator 
(Check the placement section)](https://material.io/components/progress-indicators/#linear-progress-indicators)

**Comment by ngwutadesmond** [comment]
Hi, I am working on this already and will create a PR once done.

**Comment by pawank0411** [comment]
@chydee any update?

**Comment by abdulbasit75** [comment]
I would like to work on this, please assign me.
