### ISSUE TITLE
Implement PDF/DOC Viewer

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/WhatsApp-Cleaner#23]
Currently for viewing pdf/docs app uses **third-party apps that are present on the user phone.**
**Implement PDF/Doc Viewer in the app** so that the need for third-party apps can be eliminated.

**Comment by VishnuSanal** [comment]
@pawank0411 Could I work on this? Also, Can I use third-party API?

**Comment by pawank0411** [comment]
Yes sure @VishnuSanal.
Can you specify which API?

**Comment by VishnuSanal** [comment]
@pawank0411 Thank you for your swift reply. Should I use [AndroidPdfViewer ](https://github.com/barteksc/AndroidPdfViewer) or native [PdfRenderer](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer) or the [`WebView`](https://stackoverflow.com/a/10861538/9652621) method or [Android-Pdf-Viewer-Library](https://github.com/jblough/Android-Pdf-Viewer-Library). Each one of these has its own drawbacks!

**Comment by pawank0411** [comment]
@VishnuSanal AndroidPdfViewer seems promising.

**Comment by VishnuSanal** [comment]
@pawank0411 Okay. I'll work and submit a PR...

**Comment by VishnuSanal** [comment]
@pawank0411 Sorry for the interruption. The apk size increases to 27.8MB from ~10MB after adding AndroidPdfViewer dependency. So, should I continue with this library or try using something else?

EDIT: 

Possible fix - Using [AndroidPdfViewer](https://github.com/manishkummar21/AndroidPdfViewer) 
But this requires API 21+ (now it's 19+). So with your consent, let me make this change...

**Comment by pawank0411** [comment]
@VishnuSanal you can try any other method.

**Comment by VishnuSanal** [comment]
@pawank0141 Possible fix - Using [AndroidPdfViewer](https://github.com/manishkummar21/AndroidPdfViewer)
But this requires API 21+ (now it's 19+). So with your consent, let me make this change...

**Comment by pawank0411** [comment]
@VishnuSanal  you can increase the minSDKVersion.

**Comment by VishnuSanal** [comment]
@pawank0411 I've implemented [AndroidPdfViewer](https://github.com/manishkummar21/AndroidPdfViewer). But the native PDF Viewer (even in my phone) one looks and feels far better from this library. So I'm confused about (I'm sorry to say) whether to implement this in the first place! Looking for a reply from you... Thank you

**Comment by pawank0411** [comment]
@VishnuSanal Let's connect in [LinkedIn](https://www.linkedin.com/in/pawank0411/).

**Comment by VishnuSanal** [comment]
@pawank0411 Please let's stick with GitHub!

**Comment by pawank0411** [comment]
@VishnuSanal If you have another option better than this library, then go for it.

**Comment by VishnuSanal** [comment]
Okay

**Comment by pawank0411** [comment]
And must say @VishnuSanal, you're doing a great work. 👍

**Comment by VishnuSanal** [comment]
@pawank0411 Thank you. Means a LOT!!!

**Comment by VishnuSanal** [comment]
@pawank0411 I'm afraid to say that I'm stuck. It is not that I haven't implemented, I've all the methods I mentioned above. But nothing works better than the native PDF viewer on my phone. So, you had better assign this to someone else. Sorry for wasting your time. 

PS: I look forward to contributing to this repository furthermore since this is something that actually helps users to delete unnecessary hidden files made be WhatsApp

**Comment by pawank0411** [comment]
**@VishnuSanal No problem.
And yes feel free to create new issues or can work on the existing [Issues](https://github.com/pawank0411/WhatsApp-Cleaner/issues).**
