### ISSUE TITLE
Implement Image viewer and Video player

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/WhatsApp-Cleaner#24]
Currently for viewing images or playing videos app uses **third-party apps that are present on the user phone.**
**Implement Image viewer and Video player in the app** so that the need for third-party apps can be eliminated.

**Comment by VishnuSanal** [comment]
@pawank0411 Would you allow me to work on this issue?

**Comment by pawank0411** [comment]
Yes sure @VishnuSanal
