### ISSUE TITLE
Unable to fetch details on Android 10

### ISSUE THREAD

**Issue by abdulbasit75** [Pawan0411/WhatsApp-Cleaner#37]
![Screenshot_20201024-145455_WhatsApp Cleaner.jpg](https://user-images.githubusercontent.com/46890586/97079060-5b2b9900-160a-11eb-9ff3-fc018ac00ae1.jpg)

**Comment by abdulbasit75** [comment]
Can i work on this ?

**Comment by pawank0411** [comment]
sure @abdulbasit75
