### ISSUE TITLE
Clicking on Rate App does not work

### ISSUE THREAD

**Issue by VishnuSanal** [Pawan0411/WhatsApp-Cleaner#39]
Greetings @pawank0411,

Clicking Rate App from the AlertDialog does not bring any app in the PlayStore. It shows the loading progress bar but does not load any app for a long time.

I checked the package name of the app in the PlayStore. That shows an error.

Regards

**Comment by abdulbasit75** [comment]
I would like to work on this issue, please assign me.

**Comment by pawank0411** [comment]
Hi, @VishnuSanal currently the app is not unavailable on the PlayStore.

**Comment by pawank0411** [comment]
> 
> 
> I would like to work on this issue, please assign me.

Yes, sure @abdulbasit75 but before that can you please tell me what changes you want to do ?

**Comment by VishnuSanal** [comment]
@pawank0411 Let me ask out of curiosity, Why was it removed from PlayStore? Also, ads don't appear... Is it because you disabled the AdMob account?

**Comment by pawank0411** [comment]
@VishnuSanal  **There's no issue with the app** actually, my developer account got terminated due to some reasons. :(
Even I have no access to my Admob account.

**Comment by VishnuSanal** [comment]
@pawank0411 Oh! For how long now? Did you try to revive the account? Just asking out of curiosity...😇

**Comment by pawank0411** [comment]
> 
> 
> @pawank0411 Oh! For how long now? Did you try to revive the account? Just asking out of curiosity...😇

@VishnuSanal on 24th March I received a mail regarding my account termination and as it's a life ban from google play console I can't revive my account. :-(

**Comment by VishnuSanal** [comment]
@pawank0411 Ouch! Sad to hear... What was the reason they pointed-out? How many active-users did the app have then?
