### ISSUE TITLE
Add scrollbar to content activity 

### ISSUE THREAD

**Issue by pawank0411** [Pawan0411/WhatsApp-Cleaner#6]
- add scrollbar to all the content activities  :+1:

**Comment by ngwutadesmond** [comment]
Hi, Can I take this up? I would really like to contribute if you don't mind I'll fix it and send a PR

**Comment by pawank0411** [comment]
Yes @chydee you can work on this.

**Comment by ngwutadesmond** [comment]
I sent a PR already you can check it out

**Comment by pawank0411** [comment]
merged.

**Comment by ngwutadesmond** [comment]
Okay Great

**Comment by ngwutadesmond** [comment]
I am glad I could contribute. thank you for the opportunity

**Comment by pawank0411** [comment]
Many more opportunities are on their way.

**Comment by ngwutadesmond** [comment]
Alright thanks again
